name: "template"

on:
  push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && exit 0
  deploy_test:
    needs: test
    if: ${{ !(contains(needs.test.result, 'failure')) }}
    runs-on: ubuntu-latest
    steps:
      - name: output some info
        run: echo "okay"
