name: "template"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        run: echo "aaaaaa"
      - run: sleep 10 && exit 0
  deploy_test:
    needs: test
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: output some info
        run: echo "okay"
