name: "template"

on:
  push:
    branches:
      - "*"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.event.before }}
          filters: |
            src:
              - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        run: echo "aaaaaa"
      - run: echo "weeee"
      - id: nano
        env:
           TITLE: ${{ github.event.pull_request.title }}
           MESSAGE: ${{ github.event.head_commit.message }}
        run: |
           EVENT_MESSAGE="$TITLE $(git log) $MESSAGE"
           echo $EVENT_MESSAGE
           echo "message=$EVENT_MESSAGE" >> $GITHUB_OUTPUT
  deploy_test:
    needs: test
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: output some info
        run: echo "okay"
