name: "template"

on:
  push
  
jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && exit 0
  deploy_test:
    needs: test
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: output some info
        run: echo "okay"
