name: "template"

on:
  push
  
jobs:
  template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: echo "Hello World"
    - run: curl https://api.github.com/users/nanophate/repos | jq -r '.[] |  select(.full_name == "${{ secrets.APP_NAME }}")'
    
